package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// manifestHeader explains what the file is, so the next person to edit it by
// hand understands that CI will reject the edit.
const manifestHeader = `# Generated by tools/openapicheck -write-manifest. Do not edit by hand.
#
# This is the flat list of operations the OpenAPI document promises to serve. CI
# regenerates it and fails if it differs, so the documented surface and the
# checked-in manifest can never drift apart. The check is one-directional on
# purpose: when internal/server/server.go is restored (issue #186) the manifest
# becomes a comparison between the router's registered routes and the document,
# and this file is the expected output of that comparison either way.
`

type manifest struct {
	Routes []string `yaml:"routes"`
}

// operationIDs returns the document's operations in manifest order: sorted so
// regeneration produces a stable diff.
func (d *Document) operationIDs() []string {
	ids := make([]string, 0)
	for _, op := range d.operations() {
		ids = append(ids, op.ID())
	}
	sort.Strings(ids)
	return ids
}

// writeRouteManifest regenerates the manifest from the document.
func writeRouteManifest(path string, doc *Document) error {
	ids := doc.operationIDs()
	body := manifestHeader + "\nroutes:\n"
	for _, id := range ids {
		body += "  - " + yamlScalar(id) + "\n"
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return err
	}
	return nil
}

// checkRouteManifest compares the manifest against the document in both
// directions. A route in the manifest that the document does not define is the
// failure worth shouting about: the manifest is what callers were told exists.
func checkRouteManifest(path string, doc *Document) []Finding {
	data, err := os.ReadFile(path)
	if err != nil {
		return []Finding{{Location: path, Message: fmt.Sprintf("cannot read route manifest: %v", err)}}
	}
	var m manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return []Finding{{Location: path, Message: fmt.Sprintf("cannot parse route manifest: %v", err)}}
	}

	inManifest := map[string]bool{}
	var findings []Finding
	for _, id := range m.Routes {
		if id = strings.TrimSpace(id); id == "" {
			continue
		}
		if inManifest[id] {
			findings = append(findings, Finding{path, fmt.Sprintf("route %q is listed twice", id)})
			continue
		}
		inManifest[id] = true
	}

	inDocument := map[string]bool{}
	for _, id := range doc.operationIDs() {
		inDocument[id] = true
		if !inManifest[id] {
			findings = append(findings, Finding{path, fmt.Sprintf("route %q is defined in the OpenAPI document but missing from the manifest", id)})
		}
	}

	// Report manifest entries the document does not define, in a stable order.
	var extra []string
	for id := range inManifest {
		if !inDocument[id] {
			extra = append(extra, id)
		}
	}
	sort.Strings(extra)
	for _, id := range extra {
		findings = append(findings, Finding{path, fmt.Sprintf("route %q is in the manifest but the OpenAPI document does not define it", id)})
	}

	return findings
}

// yamlScalar quotes a manifest entry when plain style would be ambiguous.
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, ":#{}[]&*!|>'\"%@`,") || strings.HasPrefix(s, " ") || strings.HasSuffix(s, " ") {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}
